version: '3.8'
services:
  cf-audit: &cf-audit
    image: geometalab/osm-conflate-cf-audit
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      # uncomment following line to enable debugging
      # DEBUG: yes
      CSV_FILE: '/tmp/audit.csv'
      DATABASE_URI: 'postgresql://cf_audit:pw@database:5432/cf_audit'
    # command: ["gunicorn", "--reload", "-b", "0.0.0.0:8080", "cf_audit:application"]
    # volumes:
    #   - ../:/app/cf-audit
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database

  migrate:
    <<: *cf-audit
    command: python migrate.py
    ports: []

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: cf_audit
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: cf_audit
